-- Add dice columns to items table for weapon damage
ALTER TABLE items
ADD COLUMN IF NOT EXISTS piercing_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS crushing_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS slashing_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS fire_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS ice_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS lightning_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS water_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS earth_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS air_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS light_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS dark_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS magic_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS poison_dice VARCHAR(10) DEFAULT NULL;

-- Add dice columns to abilities table for ability damage
ALTER TABLE abilities
ADD COLUMN IF NOT EXISTS fire_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS ice_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS lightning_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS water_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS earth_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS air_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS light_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS dark_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS magic_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS poison_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS piercing_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS crushing_dice VARCHAR(10) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS slashing_dice VARCHAR(10) DEFAULT NULL;

-- Add comments for documentation
COMMENT ON COLUMN items.piercing_dice IS 'Dice notation for piercing damage (e.g., "1d6" = roll 0-6)';
COMMENT ON COLUMN items.crushing_dice IS 'Dice notation for crushing damage (e.g., "1d5" = roll 0-5)';
COMMENT ON COLUMN items.slashing_dice IS 'Dice notation for slashing damage (e.g., "1d6" = roll 0-6)';
COMMENT ON COLUMN abilities.fire_dice IS 'Dice notation for fire damage from this ability';

